### ISSUE TITLE
Doc: provide minimum requirement

### ISSUE THREAD

**Issue by juhivarshney-20** [konveyor/tackle-windup-api#45]
**Is your feature request related to a problem? Please describe.**
While deploying windup-api on OCP 4x16 3 nodes cluster, getting error in PVC claim.

**Describe the solution you'd like**
Provide minimum OCP cluster configuration requirement or is there any specific requirement for storage in cluster.

<img width="565" alt="windup-api" src="https://user-images.githubusercontent.com/66256842/146190594-1900c7d6-12ae-423d-99f3-43f858578917.png">

**Comment by rromannissen** [comment]
@juhivarshney-20 are you blocked or could you figure out a workaround? We will have this documented for sure, but let me know if you need some assistance deploying the prototype.

**Comment by juhivarshney-20** [comment]
Yes we are blocked, tried few things but those didn't work. We need assistance as soon as possible for deploying the prototype on OCP.

**Comment by rromannissen** [comment]
@juhivarshney-20 I've been told by @mrizzi that you are not blocked anymore by this. Could you please confirm?

**Comment by juhivarshney-20** [comment]
@rromannissen Yes able to deploy on OCP, with few modifications in yaml file.
